/**
 * Fixture shapes aligned with analytic_castle_backend tests/test_phase8_integration.py
 * and app/ai agent models. Used by unit tests — not sent as fake live API data.
 */
import type { Phase8Analysis } from "@/features/ai/types";

export const phase8AnalysisFixture: Phase8Analysis = {
  session_id: "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
  data_analyst: {
    interpretation:
      "Revenue peaked in February at 105 and fell to 60 in March.",
    summary: "Total revenue across three months was 265.",
    comparisons: "March revenue of 60 is below February's 105.",
    conclusions: ["March revenue fell to 60."],
    confidence_score: "MEDIUM",
    confidence_reasoning: "Three months is a small sample.",
  },
  trend: {
    direction: "DECREASING",
    growth_rate_percent: -40,
    series: {
      period_column: "month",
      value_column: "revenue",
      point_count: 3,
      skipped_row_count: 0,
      reordered: false,
      first_period: "2024-01",
      last_period: "2024-03",
      first_value: 100,
      last_value: 60,
      minimum_value: 60,
      maximum_value: 105,
      direction: "DECREASING",
      total_change: -40,
      growth_rate_percent: -40,
      average_period_change_percent: -20,
      direction_changes: 1,
      comparisons: [
        {
          previous_period: "2024-01",
          period: "2024-02",
          previous_value: 100,
          value: 105,
          absolute_change: 5,
          percent_change: 5,
          direction: "INCREASING",
          significant: false,
        },
        {
          previous_period: "2024-02",
          period: "2024-03",
          previous_value: 105,
          value: 60,
          absolute_change: -45,
          percent_change: -42.9,
          direction: "DECREASING",
          significant: true,
        },
      ],
      significant_changes: [
        {
          previous_period: "2024-02",
          period: "2024-03",
          previous_value: 105,
          value: 60,
          absolute_change: -45,
          percent_change: -42.9,
          direction: "DECREASING",
          significant: true,
        },
      ],
      notes: [],
    },
    summary: "Revenue fell from 100 in 2024-01 to 60 in 2024-03.",
    direction_explanation: "The series is decreasing after February.",
    period_comparisons: "2024-03 fell against 2024-02.",
    significant_changes: "2024-03 is a significant decline.",
    conclusions: ["Revenue declined in 2024-03."],
    confidence_score: "MEDIUM",
    confidence_reasoning: "Only three periods are available.",
  },
  anomaly: {
    anomaly_count: 1,
    highest_severity: "HIGH",
    scan: {
      analyzed: true,
      numeric_columns: ["revenue"],
      scanned_row_count: 3,
      period_column: "month",
      column_statistics: {},
      anomalies: [
        {
          column: "revenue",
          anomaly_type: "UNEXPECTED_CHANGE",
          severity: "HIGH",
          method: "period_change",
          value: 60,
          row_index: 2,
          period: "2024-03",
          previous_value: 105,
          percent_change: -42.9,
          expected_low: 90,
          expected_high: 120,
          score: 2.1,
          evidence: "2024-03 fell against 2024-02 in revenue.",
        },
      ],
      notes: [],
    },
    summary: "One unexpected decline was detected in revenue.",
    outliers: "No statistical outlier was detected.",
    unexpected_changes: "2024-03 fell against 2024-02 in revenue.",
    threshold_breaches: "No threshold breach was detected.",
    conclusions: ["2024-03 declined unexpectedly in revenue."],
    confidence_score: "MEDIUM",
    confidence_reasoning: "Three periods is a small sample.",
  },
  root_cause: {
    summary: "Demand weakening is the leading candidate explanation.",
    primary_cause: "Demand weakened in March.",
    hypotheses: [
      {
        rank: 1,
        statement: "Demand weakened in March.",
        contributing_factors: ["Seasonal slowdown"],
        supporting_evidence: "Revenue fell from 105 to 60 in 2024-03.",
        contradicting_evidence: null,
        confidence_score: "MEDIUM",
        confidence_reasoning: "Limited corroborating dimensions.",
        investigation_question: null,
      },
    ],
    evidence: [],
    additional_queries_run: 0,
    confidence_score: "MEDIUM",
    confidence_reasoning: "Hypothesis rests on a short series.",
    notes: [],
  },
  insight: {
    summary: "March revenue reversal is the primary business finding.",
    top_insight: "Revenue reversed in March",
    insights: [
      {
        rank: 1,
        title: "Revenue reversed in March",
        insight:
          "Customer retention dipped as revenue fell 42.9% month over month.",
        metric: "revenue",
        business_impact: "Lower March revenue reduces quarterly run-rate.",
        supporting_evidence:
          "Revenue moved from 105 in 2024-02 to 60 in 2024-03.",
        priority: "HIGH",
        confidence_score: "HIGH",
        confidence_reasoning: "Directly observed in the result set.",
      },
    ],
    key_metrics: [
      {
        column: "revenue",
        value_count: 3,
        total: 265,
        average: 88.333,
        minimum: 60,
        maximum: 105,
      },
    ],
    data_gaps: [],
    confidence_score: "HIGH",
    confidence_reasoning: "Metrics and trends align.",
    notes: [],
  },
  recommendation: {
    summary: "Investigate March demand drivers before expanding spend.",
    top_recommendation: "Review March campaign mix",
    recommendations: [
      {
        rank: 1,
        title: "Review March campaign mix",
        recommendation:
          "Audit marketing channels active in March against February.",
        evidence_reference: "Revenue reversed in March",
        supporting_evidence: "The March decline is concentrated in revenue.",
        expected_outcome:
          "Identify whether demand or channel mix drove the drop.",
        assumptions: ["Campaign calendars are available"],
        risks: ["May not isolate external demand shocks"],
        impact: "HIGH",
        feasibility: "MEDIUM",
        priority: "HIGH",
        confidence_score: "MEDIUM",
        confidence_reasoning:
          "Evidence supports investigation, not a guaranteed fix.",
      },
    ],
    data_gaps: [],
    confidence_score: "MEDIUM",
    confidence_reasoning: "Recommendations assume operational capacity.",
    notes: [],
  },
  evaluation: {
    session_id: "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
    generated_at: "2026-09-24T06:00:00Z",
    agents: [
      {
        agent: "DATA_ANALYST",
        checks: [
          {
            agent: "DATA_ANALYST",
            check_id: "has_conclusions",
            dimension: "COMPLETENESS",
            status: "PASS",
            method: "VERIFIED",
            detail: "Conclusions were present.",
            evidence_reference: "DataAnalysisResult.conclusions",
          },
        ],
        verified_passed: 1,
        verified_failed: 0,
        estimated_passed: 0,
        estimated_warnings: 0,
        skipped: 0,
        verified_correct: true,
        estimated_quality_score: 1,
      },
    ],
    agents_not_evaluated: [],
    metrics: {
      agents_evaluated: 1,
      checks_run: 1,
      verified_checks: 1,
      verified_failures: 0,
      estimated_checks: 0,
      estimated_warnings: 0,
      skipped_checks: 0,
      verified_pass_rate: 1,
      estimated_quality_score: 1,
      query_duration_ms: null,
    },
    verified_correct: true,
    notes: [],
  },
};

/** Partial pipeline: only analyst + insight (acceptance criterion). */
export const phase8PartialFixture: Phase8Analysis = {
  data_analyst: phase8AnalysisFixture.data_analyst,
  insight: phase8AnalysisFixture.insight,
};
